name: DynamicEconomy
version: '${version}'
main: dev.n1xend.dynamiceconomy.DynamicEconomy
description: '${description}'
api-version: '1.21'
author: '${author}'

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true

permissions:
  dynamiceconomy.shop:
    description: Access to the market shop
    default: true
  dynamiceconomy.admin:
    description: Admin access
    default: op
  dynamiceconomy.bypass.cooldown:
    description: Bypass sell cooldown
    default: op
